apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: forecasts
  name: forecasts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forecasts
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/app: "true"
        io.kompose.service: forecasts
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              value: "9006"
            - name: PULSAR_URI
              value: pulsar://pulsar:6650
          image: trading-forecasts:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9006/health
            failureThreshold: 15
            initialDelaySeconds: 120
            periodSeconds: 2
            timeoutSeconds: 5
          name: forecasts
          ports:
            - containerPort: 9006
          resources: {}
      restartPolicy: Always
status: {}
